version: 2
updates:
  # Bundler Configuration
  - package-ecosystem: "bundler"
    directory: "/"
    # Labels to set on pull requests
    labels:
      - "gem"
      - "dependencies"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "bundle"
    groups:
      # Rails Project Dependencies
      rails:
        exclude-patterns:
          - "rubocop*"
      # Rails Linter Dependencies
      ruby-linter:
        patterns:
          - "rubocop*"

  # NPM Package Configuration
  - package-ecosystem: "npm"
    directory: "/"
    # Labels to set on pull requests
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm"
    groups:
      # Javascript Dependencies
      js:
        exclude-patterns:
          - "postcss*"
          - "autoprefixer"
      # CSS Bundler Dependencies
      css-bundling:
        patterns:
          - "postcss*"
          - "autoprefixer"
