name: Setup Project
runs:
  steps:
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up database schema
      run: bin/rails db:schema:load
