name: My Action
description: cacahue
runs:
  using: "composite"
  steps:
    - name: Step 1
      shell: bash
      run: echo "This is step 1"
    - name: Step 2
      shell: bash
      run: echo "This is step 2"
