name: Setup Rails Project ()
description: cacahue
runs:
  using: "composite"
  steps:
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up database schema
      shell: bash
      run: bundle exec rails db:schema:load
